### ISSUE TITLE
CRITICAL slack_to_discord Failed to finish import!

### ISSUE THREAD

**Issue by paveldoreuli** [pR0Ps/slack-to-discord#13] opened 2022-10-05 21:39 UTC
Thank you for support! I'm reinstall new version, but still have same error(
I'm also attach one json file from channel #obchiy for test. there no sensetive information)
![Screenshot 2022-10-06 at 00 26 06](https://user-images.githubusercontent.com/114866573/194167623-95cd69b5-24b3-4305-858a-4b4b74005783.png)
[obchiy.zip](https://github.com/pR0Ps/slack-to-discord/files/9719121/obchiy.zip)

_Originally posted by @paveldoreuli in https://github.com/pR0Ps/slack-to-discord/issues/12#issuecomment-1269002942_

**Comment by paveldoreuli** [comment] 2022-10-05 21:42
Sorry, I tried to reopen the old issue, but did not find how to do it

**Comment by pR0Ps** [comment] 2022-10-06 03:15
You're running an older version. This fix for this issue was done in cb790c72 - it changed the line of code that's shown in your error message to something else.

I've just uploaded the latest version to PyPI, so you should be able to install it from there. Try running `pip uninstall slack-to-discord` to remove your current version, then `pip install slack-to-discord` to reinstall it. You should see the message "Successfully installed slack-to-discord-1.0.0" after it's installed.

**Comment by paveldoreuli** [comment] 2022-10-06 19:39
Still don't work( I reinstall v 1.0.0
![Screenshot 2022-10-06 at 22 36 26](https://user-images.githubusercontent.com/114866573/194403565-3d9f0ce3-7bec-40cb-bd69-5e1ccbddb7bc.png)
![Screenshot 2022-10-06 at 22 36 41](https://user-images.githubusercontent.com/114866573/194403587-4f4e1bd6-5bc8-48d5-b992-2b1303885db0.png)

**Closed** 2022-10-07 00:45 UTC

**Comment by pR0Ps** [comment] 2022-10-07 00:54
The latest commit should fix this issue.

Install it via `pip uninstall slack-to-discord` then `pip install git+https://github.com/pR0Ps/slack-to-discord` . Once I can confirm that your import fully works, I'll push an update to PyPI.

**Comment by paveldoreuli** [comment] 2022-10-08 13:22
Hi. Thanks a lot! It works!!!! 
Is it possible to add option to escape day boundaries between messages? 
How can I donate to you?

**Comment by paveldoreuli** [comment] 2022-10-08 13:24
Hello. Thanks a lot! It works!!!!
Is it possible to add option to escape day boundaries between messages?
How can I donate to you?

**Comment by pR0Ps** [comment] 2022-10-08 13:35
(deleted a dupe comment)
You'll want:

```python
DATE_SEPARATOR = None
```
(note the lack of `"`'s around the `None`

Also, you might want to change the `MSG_FORMAT` to
```python
MSG_FORMAT = "`{date} {time}` {text}"
```
So that each message has the date in it as well as the time.

**Comment by paveldoreuli** [comment] 2022-10-08 13:40
Thank you!
